version: '3'

services:
  db:
    image: mysql:8.0.42
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '123456789'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'yii2'
      MYSQL_USER: 'yii'
      MYSQL_PASSWORD: '123456789'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'yii2-mysql:/var/lib/mysql'
    networks:
      - yii2

networks:
    yii2:
      driver: bridge

volumes:
    yii2-mysql:
      driver: local
